{% set name = "bleach" %}
{% set version = "6.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 123e894118b8a599fd80d3ec1a6d4cc7ce4e5882b1317a7e1ba69b56e95f991f

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    # for html5lib which is vendored, see https://github.com/mozilla/bleach/tree/main/bleach/_vendor
    - webencodings
  run_constrained:
    - tinycss2 >=1.1.0,<1.5 # extra:css

test:
  imports:
    - bleach
  source_files:
    - tests
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest tests -v


about:
  home: https://github.com/mozilla/bleach
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Easy, allowlist-based HTML-sanitizing tool
  description: |
    Bleach is an allowlist-based HTML sanitizing library that escapes or
    strips markup and attributes.
  dev_url: https://github.com/mozilla/bleach
  doc_url: https://bleach.readthedocs.io/

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
