{% set name = "bleach" %}
{% set version = "6.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f3b91b1c0a02bb9a78b5a454c92506aa0fdf197e1d5e114d2e00c6f64306d22
  patches:
    # html5lib is unvendored, deleted html5lib files from the _vendor folder, updated imports in html5lib_shim.py and test_clean.py to use html5lib from the basic conda environment.
    - patches/0001-unvendor-html5lib.patch
    - patches/0002-update-clean-test.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - html5lib ==1.1
    - webencodings
  run_constrained:
    # css
    - tinycss2 >=1.1.0,<1.5

test:
  source_files:
    - tests
  imports:
    - bleach
  commands:
    - pip check
    - pytest tests -v
  requires:
    - pip
    - pytest

about:
  home: https://github.com/mozilla/bleach
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Easy, whitelist-based HTML-sanitizing tool
  description: |
    Bleach is an allowed-list-based HTML sanitizing library that escapes or
    strips markup and attributes.
  dev_url: https://github.com/mozilla/bleach
  doc_url: https://bleach.readthedocs.io

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
