travis:
  secure:
    BINSTAR_TOKEN: F+g7A1KmR72Ab4LDwRL+bElr1knL2ynOXxdmfj22awXKVmpnFDdxDhxAXlGaEVSxvmYs9DrF2a+1XsOEYFXzpc1ABwgCAF5JJ6GlR5i5pzOPRdEhk705CgAsR55CFSqAwdfleot2695J5VzgIjxD/NGWiwUdCRGnEYA9GHvHjbKt+b4d/Bzntab+WIjA0LBgeIEDbc6wzYaHRYhPRB8a5OTD8nat+g8bxioQqofjSP4cpNbR/aJmyCWXuoU09Vtu1Bu7oSc4yHfyxkkomy5hc4m2aC09ipG5krayTARuQSlh2AZLSFzDY2FZiMQYZPLj36Om05hcDJ3BSLOMqmMluBMB5GsW6f+o3FGrd9E7q3zd7tidfISrg2HQq69qvbkhnHm0MnojGag+ZHgy0fvuLK7tkBdVsJxw7IIdIeL5io1YyZb1mDIRiA/1xO1X7bE9oNdXvUv68WS41kRl9VteQXjetpDHIHI24/DXu1JMYVY/COPkSmHuK00MFZfsEbQf09GJlE/AsptukOYP28OdDwNVoMdUm3HBVwq1zpFYE+KykdhF7VdvWm4TYlNjUZlLqPTgKsRVnbdkPk9dNVZNNj09kLCOlLum0Vl1EReYiasiCa/5vSvPUG6A/VGBbG9/jTUvm2Pvz7O5wOSgf8ZHuYztDt4pwO/5JRRxDPCnydE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
