travis:
  secure:
    BINSTAR_TOKEN: NPOxE34grt5YRRx45lQjV/b+ngnqPv9sU7WhMmQD4TJCsG3HU+AGeK0E0BNjahJO8LIYm+T3tWdf0ZWvjyXsoX7rsXsbD99pHAAfKJ5nbxtiFfbszsSAdJzQT+HcN+ShN4OEjlnK6Ob8KYMNOUb93USdssrHuU8XJYSc0WgVvWb2JjOWOLA5qtBJc235ciLFJMpdF5Q2nu8anN3vzRgFPjJiNHatZRm6CVDJCGlBycOlG86iPv4i9jzvt4s8a8tQ5+EgC7I5oAsaMmaQEMIGrKbwoMAWagAiX2IMa9c8sZXfpCLDGJlaF3WBxfOu9gcU0qHQh1yAjFOS/dW8AapWVjf1vyWh2HPd6gnrbSZvj9YOflO1C+LIbt7s+J/23vBD2RNPC3pFIKMjlknfDFD/pSF1sJ4W6RwEva4mU2EFIWw1F7vAc/SJrmqaQPSYTFpPAhvoYtAS9iPfO3LMohT7Mvt5tXpEbehAxH2u3TxPQTqUCM9z3me1+YQS9XfLS0Ls291gnpVWyOtnQKadxyKgFC9S3isXvlCrhwteFf/4p9aa5iQs7L4n0BZHGp393xJTaIWEJgK2F7TegM3gIhjfGAlXmVBNu0WdHGS+nbSPF3Wcp/SWP46slVUK6jkqFmkV5TP/pi5tM+q7AEtLJevcUDke/AXgfN/o5oz25w73br8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
