travis:
  secure:
    BINSTAR_TOKEN: B+hv/2cIGWeVP45H0wk3pQctd87xm0UZ96+5XdFUUQ7i72rpmc5lK5vve9xt8AmVS0eSHg10EkPfEr1sUrg/h4Cpd6dUXUc5spD7L5jOKYPGzbyklg7aYTJAmyVSaJtpLITACdpbulsbNr8/f8cvK4uqt3I2XYdZ+u8qnsUjsMUmEr6eMY7ZHLbgbPNrvABCHElJMkJVVoHC52RxXc7N+3IZHQg4Xn9YlFkdnXAgN1j+jRXo+UMG5KwVZDYKO4qavOuEMf44fJM14VUta6S2WD755eZyU/YFmmLnYYNCMk7c1vva3//j6NQXArKsCTdI4HQzyu568NL1KvnLjLfZan7mrKJfj9b3Oy/Xy9NMElTzY4YU11gyQSb+dQ7Olyd1u1Xn64xp1U8aYMmFycUa0C7N509UgWRkmCilUqusCr+jMV/s8AjewIV9DR2LCoPgC1aTCOjcvvMkyagsfBbFnPwZvWCfNEXP8/KZbnfy3G/fNLY9wO76RPXDcPOryDk1WCam9jfNMl7FoFjmAovFJHaJlbpV99IK3sgKoPxOZdIyagWYrVBlreJWPafbTS6vCqGLfXc3CN+hvr684a8PGpa6bem48wG7DQfZk7JsbLOnn6X+Q/Xnpts0bZtcbmoZsS7463WWc/UKddK+xQYq8o6zZ5UeSpUpAayphVceRPM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
